export const Posts = [
  {
    id: 1,
    desc: "Cooked a delicious and healthy lunch today :)",
    photo: "assets/post/1.jpg",
    date: "30 mins ago",
    userId: 1,
    likes: 9,
    comments: 3,
  },
  {
    id: 2,
    photo: "assets/post/2.jpg",
    date: "2 hours ago",
    userId: 2,
    likes: 12,
    comments: 5,
  },
  {
    id: 3,
    desc: "What a beautiful sunset today!",
    photo: "assets/post/3.jpg",
    date: "4 hours ago",
    userId: 3,
    likes: 5,
    comments: 9,
  },
  {
    id: 4,
    photo: "assets/post/4.jpg",
    date: "5 hours ago",
    userId: 4,
    likes: 9,
    comments: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpg",
    date: "7 hours ago",
    userId: 5,
    likes: 13,
    comments: 19,
  },
];
